# Kubernetes Secrets Configuration
# IMPORTANT: Replace all values with your actual secrets before applying
# You can also use kubectl to create secrets:
# kubectl create secret generic ml-router-secrets --from-env-file=.env

apiVersion: v1
kind: Secret
metadata:
  name: ml-router-secrets
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  # Example: echo -n "your-secret-value" | base64
  
  database-url: cG9zdGdyZXNxbDovL3VzZXJuYW1lOnBhc3N3b3JkQGxvY2FsaG9zdDo1NDMyL21scm91dGVy
  session-secret: eW91ci12ZXJ5LWxvbmctcmFuZG9tLXNlY3JldC1rZXktaGVyZQ==
  jwt-secret: and0LXNpZ25pbmctc2VjcmV0LWhlcmU=
  openai-api-key: c2steW91ci1vcGVuYWkta2V5LWhlcmU=
  anthropic-api-key: c2stYW50LXlvdXItYW50aHJvcGljLWtleS1oZXJl
  google-api-key: QUl6YS15b3VyLWdvb2dsZS1rZXktaGVyZQ==
  xai-api-key: eGFpLXlvdXIteGFpLWtleS1oZXJl
  perplexity-api-key: cHBseC15b3VyLXBlcnBsZXhpdHkta2V5LWhlcmU=
  cohere-api-key: eW91ci1jb2hlcmUta2V5LWhlcmU=
  mistral-api-key: eW91ci1taXN0cmFsLWtleS1oZXJl
  huggingface-api-key: aGYteW91ci1odWdnaW5nZmFjZS1rZXktaGVyZQ==